# Generated by Django 3.2.18 on 2023-12-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100)),
                ('nkk', models.BigIntegerField()),
                ('nik', models.BigIntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('sts_kawin', models.CharField(max_length=20)),
                ('kelamin', models.CharField(max_length=1)),
                ('alamat', models.TextField()),
                ('rt', models.IntegerField()),
                ('rw', models.IntegerField()),
                ('disabilitas', models.IntegerField()),
                ('ektp', models.CharField(max_length=100)),
                ('tps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Koordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100)),
                ('nkk', models.BigIntegerField()),
                ('nik', models.BigIntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('sts_kawin', models.CharField(max_length=20)),
                ('kelamin', models.CharField(max_length=1)),
                ('alamat', models.TextField()),
                ('rt', models.IntegerField()),
                ('rw', models.IntegerField()),
                ('disabilitas', models.IntegerField()),
                ('ektp', models.CharField(max_length=100)),
                ('tps', models.IntegerField()),
                ('foto_ktp', models.ImageField(upload_to='foto_ktp/')),
                ('wilayah_kerja', models.CharField(max_length=100)),
                ('jumlah_rekrutan', models.IntegerField()),
                ('no_hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaftarPemilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_ktp', models.ImageField(upload_to='foto_ktp/')),
                ('data_warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemilu.datawarga')),
                ('koordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemilu.koordinator')),
            ],
        ),
    ]
