# Generated by Django 3.2.18 on 2023-12-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Koordinator',
            new_name='DataKoordinator',
        ),
    ]
