# Generated by Django 3.2.18 on 2023-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0004_auto_20231214_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakoordinator',
            name='ektp',
            field=models.CharField(max_length=255),
        ),
    ]
