# Generated by Django 3.2.18 on 2023-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0005_alter_datakoordinator_ektp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakoordinator',
            name='jumlah_rekrutan',
            field=models.IntegerField(default=0),
        ),
    ]
