# Generated by Django 3.2.18 on 2023-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0006_alter_datakoordinator_jumlah_rekrutan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapemilih',
            name='data_warga',
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='disabilitas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='ektp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='kelamin',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='nama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='nik',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='nkk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='rt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='rw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='sts_kawin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datapemilih',
            name='tps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
