# Generated by Django 3.2.18 on 2023-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0008_auto_20231221_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakoordinator',
            name='kabupaten_bertugas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datakoordinator',
            name='kecamatan_bertugas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datakoordinator',
            name='kelurahan_bertugas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datakoordinator',
            name='tps_bertugas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
