# Generated by Django 3.2.18 on 2023-12-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0009_auto_20231221_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datakoordinator',
            name='nama_wilayah',
        ),
    ]
