# Generated by Django 3.2.18 on 2023-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0010_remove_datakoordinator_nama_wilayah'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanWilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten_bangka', models.BooleanField(default=True)),
                ('kabupaten_bangka_selatan', models.BooleanField(default=True)),
                ('kabupaten_bangka_tengah', models.BooleanField(default=True)),
                ('kabupaten_bangka_barat', models.BooleanField(default=True)),
                ('kota_pangkal_pinang', models.BooleanField(default=True)),
                ('kabupaten_belitung', models.BooleanField(default=True)),
                ('kabupaten_belitung_timur', models.BooleanField(default=True)),
            ],
        ),
    ]
