# Generated by Django 3.2.18 on 2024-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0012_auto_20231225_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPemilu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten', models.CharField(max_length=255)),
                ('kecamatan', models.CharField(max_length=255)),
                ('kelurahan', models.CharField(max_length=255)),
                ('tps', models.IntegerField()),
                ('calon_1_2019', models.IntegerField()),
                ('calon_2_2019', models.IntegerField()),
                ('calon_3_2019', models.IntegerField()),
                ('suara_Partai_2019', models.IntegerField()),
                ('calon_1_2024', models.IntegerField()),
                ('total_suara_2024', models.IntegerField()),
            ],
        ),
    ]
