# Generated by Django 5.0 on 2024-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0012_auto_20231225_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakoordinator',
            name='no_hp',
            field=models.BigIntegerField(verbose_name='No HP'),
        ),
    ]
