# Generated by Django 3.2.18 on 2024-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0013_datapemilu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapemilu',
            name='tps',
            field=models.CharField(max_length=255),
        ),
    ]
