# Generated by Django 5.0 on 2024-01-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0013_alter_datakoordinator_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakoordinator',
            name='no_hp',
            field=models.CharField(max_length=30, verbose_name='No HP'),
        ),
    ]
