# Generated by Django 5.0 on 2024-01-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pemilu', '0014_alter_datakoordinator_no_hp'),
        ('Pemilu', '0014_alter_datapemilu_tps'),
    ]

    operations = [
    ]
